services:
  - type: web
    name: bitespeed-identity-reconciliation
    env: node
    region: oregon
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: PORT
        value: 10000
